-name: variables from files 
 hosts: localhost #managing the ansible server itself
 var_files: #here we can give list of variables
 - variables.yaml
 tasks:
 - name: printing variables
   ansible.builtin.debug:
     msg: "we are learning{{NAME}}, Duration is: {{DURATION}}, student is {{STUDENT}}"

