-name: variables from files 
#managing the ansible server itself
 hosts: 172.31.83.0 
 var_files: #here we can give list of variables
 - variables.yaml
 tasks:
 - name: printing variables
   ansible.builtin.debug:
     msg: "we are learning{{NAME}}, Duration is: {{DURATION}}, student is {{STUDENT}}"

